# Generated by Django 3.0.8 on 2020-07-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
